### ISSUE TITLE
 build-all.sh fails with AttributeError: module 'attr' has no attribute 'define'

### ISSUE THREAD

**Issue by rstar900** [Xilinx/finn-examples#46]
Successfully installed finn
WARNING: Unable to find /settings64.sh
WARNING: Functionality dependent on Vitis will not be available.
WARNING: If you need Vitis, ensure VITIS_PATH is set correctly and mounted into the Docker container.
Found Vivado at /tools/Xilinx/Vivado/2022.1
Found Vitis HLS at /tools/Xilinx/Vitis_HLS/2022.1
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/pdb.py", line 1704, in main
    pdb._runscript(mainpyfile)
  File "/opt/conda/lib/python3.8/pdb.py", line 1573, in _runscript
    self.run(statement)
  File "/opt/conda/lib/python3.8/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/rstar900/git_repos/finn-examples/build/bnn-pynq/build.py", line 1, in <module>
    import finn.builder.build_dataflow as build
  File "/home/rstar900/git_repos/finn-examples/build/finn/src/finn/builder/build_dataflow.py", line 29, in <module>
    import clize
  File "/opt/conda/lib/python3.8/site-packages/clize/__init__.py", line 7, in <module>
    from clize.parser import Parameter
  File "/opt/conda/lib/python3.8/site-packages/clize/parser.py", line 14, in <module>
    from sigtools import modifiers
  File "/opt/conda/lib/python3.8/site-packages/sigtools/__init__.py", line 28, in <module>
    from sigtools.specifiers import signature
  File "/opt/conda/lib/python3.8/site-packages/sigtools/specifiers.py", line 42, in <module>
    from sigtools import _util, modifiers, signatures, _specifiers
  File "/opt/conda/lib/python3.8/site-packages/sigtools/modifiers.py", line 36, in <module>
    from sigtools import _util, _specifiers, _signatures
  File "/opt/conda/lib/python3.8/site-packages/sigtools/_specifiers.py", line 23, in <module>
    from sigtools import _signatures, _util
  File "/opt/conda/lib/python3.8/site-packages/sigtools/_signatures.py", line 104, in <module>
    @attr.define(eq=False)
AttributeError: module 'attr' has no attribute 'define'

**Comment by rstar900** [comment]
https://github.com/Xilinx/finn-examples/issues/43 already another issue
